FROM python:3.11.7

# create environment
WORKDIR /server
COPY .src/ /server/src/
COPY requirements.txt /server

# install dependencies
RUN pip install -r requirements.txt

# set some default environment variables
ENV POSTGRES_DATABASE_IP = "127.0.0.1"
ENV POSTGRES_DATABASE_PORT = 5432
ENV REACT_FRONTEND_IP = "127.0.0.1"
ENV REACT_FRONTEND_PORT = "80"

# expose API port
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]