[tool.poetry]
name = "concertos"
version = "0.1.0"
description = ""
authors = ["reezuleanu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
pytest = "^8.1.1"
django = "^5.0.4"
djangorestframework = "^3.15.1"
flake8 = "^7.0.0"
django-cors-headers = "^4.3.1"
requests = "^2.32.2"
django-cities-light = "^3.10.1"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.1.0"
pydantic = "^2.11.4"
pydantic-settings = "^2.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
