# Generated by Django 5.0.4 on 2024-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='event_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
