# Generated by Django 5.0.4 on 2024-07-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_device_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=13),
        ),
    ]
