# Generated by Django 5.0.4 on 2024-07-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_device_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
