# Generated by Django 5.0.4 on 2024-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_customvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvariable',
            name='user_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
