# Generated by Django 5.0.4 on 2024-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_customvariable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvariable',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
