# Generated by Django 5.0.4 on 2024-07-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_customvariable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=15),
        ),
    ]
