# Generated by Django 5.0.4 on 2024-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=256)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
    ]
