# Generated by Django 5.0.4 on 2024-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
